# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: comm.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ncomm.proto\"\x87\x01\n\x05log_m\x12\x0b\n\x03lid\x18\x01 \x01(\x03\x12\r\n\x05\x63term\x18\x02 \x01(\x03\x12\x0e\n\x06pfxlen\x18\x03 \x01(\x03\x12\x0f\n\x07pfxterm\x18\x04 \x01(\x03\x12\x14\n\x0c\x63ommitlength\x18\x05 \x01(\x03\x12\r\n\x05lease\x18\x06 \x01(\x01\x12\x0e\n\x06suffix\x18\x07 \x03(\t\x12\x0c\n\x04type\x18\x08 \x01(\t\"\\\n\x05log_r\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0c\n\x04term\x18\x02 \x01(\x03\x12\x0b\n\x03\x61\x63k\x18\x03 \x01(\x03\x12\r\n\x05lease\x18\x04 \x01(\x01\x12\x0f\n\x07success\x18\x05 \x01(\x08\x12\x0c\n\x04type\x18\x06 \x01(\t\"$\n\x06setmsg\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"\x15\n\x06getmsg\x12\x0b\n\x03key\x18\x01 \x01(\t\"3\n\x05reply\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\x12\x0b\n\x03lID\x18\x02 \x01(\x03\x12\x0f\n\x07success\x18\x03 \x01(\x08\"I\n\x08req_vote\x12\r\n\x05\x63term\x18\x01 \x01(\x03\x12\x0b\n\x03\x63ID\x18\x02 \x01(\x03\x12\x0f\n\x07\x63loglen\x18\x03 \x01(\x03\x12\x10\n\x08\x63logterm\x18\x04 \x01(\x03\"L\n\x0freq_vote_result\x12\x0c\n\x04term\x18\x01 \x01(\x03\x12\n\n\x02ID\x18\x02 \x01(\x03\x12\x0f\n\x07granted\x18\x03 \x01(\x08\x12\x0e\n\x06pltime\x18\x05 \x01(\x01\x32P\n\x04raft\x12\x1a\n\x06LogReq\x12\x06.log_m\x1a\x06.log_r\"\x00\x12,\n\x0bRequestVote\x12\t.req_vote\x1a\x10.req_vote_result\"\x00\x32=\n\x07svr_clt\x12\x18\n\x03set\x12\x07.setmsg\x1a\x06.reply\"\x00\x12\x18\n\x03get\x12\x07.getmsg\x1a\x06.reply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'comm_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_LOG_M']._serialized_start=15
  _globals['_LOG_M']._serialized_end=150
  _globals['_LOG_R']._serialized_start=152
  _globals['_LOG_R']._serialized_end=244
  _globals['_SETMSG']._serialized_start=246
  _globals['_SETMSG']._serialized_end=282
  _globals['_GETMSG']._serialized_start=284
  _globals['_GETMSG']._serialized_end=305
  _globals['_REPLY']._serialized_start=307
  _globals['_REPLY']._serialized_end=358
  _globals['_REQ_VOTE']._serialized_start=360
  _globals['_REQ_VOTE']._serialized_end=433
  _globals['_REQ_VOTE_RESULT']._serialized_start=435
  _globals['_REQ_VOTE_RESULT']._serialized_end=511
  _globals['_RAFT']._serialized_start=513
  _globals['_RAFT']._serialized_end=593
  _globals['_SVR_CLT']._serialized_start=595
  _globals['_SVR_CLT']._serialized_end=656
# @@protoc_insertion_point(module_scope)
