# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mprd.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nmprd.proto\"F\n\x07red_req\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x14\n\x0cmapper_ports\x18\x02 \x03(\x03\x12\t\n\x01\x43\x18\x03 \x01(\x03\x12\x0e\n\x06iterno\x18\x04 \x01(\t\"\"\n\x04\x64\x61ta\x12\x0b\n\x03\x63id\x18\x01 \x01(\t\x12\r\n\x05point\x18\x02 \x03(\x02\"\x1b\n\x07\x61lldata\x12\x10\n\x01\x64\x18\x01 \x03(\x0b\x32\x05.data\"v\n\x0b\x44\x61taRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\x12\n\n\x02si\x18\x02 \x01(\x03\x12\n\n\x02\x65i\x18\x03 \x01(\x03\x12\n\n\x02nl\x18\x04 \x01(\x03\x12\n\n\x02nr\x18\x05 \x01(\x03\x12\x19\n\x08\x63\x65ntroid\x18\x06 \x03(\x0b\x32\x07.points\x12\x0e\n\x06iterno\x18\x07 \x01(\t\"\x18\n\x06points\x12\x0e\n\x06points\x18\x01 \x03(\x02\"+\n\x06\x63\x65nt_p\x12\x0b\n\x03\x63id\x18\x01 \x01(\t\x12\t\n\x01x\x18\x02 \x01(\x02\x12\t\n\x01y\x18\x03 \x01(\x02\"2\n\x0c\x44\x61taResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\x12\x12\n\x01\x64\x18\x02 \x03(\x0b\x32\x07.cent_p2P\n\x06Mapper\x12\'\n\x06Mapper\x12\x0c.DataRequest\x1a\r.DataResponse\"\x00\x12\x1d\n\x08get_data\x12\x05.data\x1a\x08.alldata\"\x00\x32/\n\x07Reducer\x12$\n\x07Reducer\x12\x08.red_req\x1a\r.DataResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mprd_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_RED_REQ']._serialized_start=14
  _globals['_RED_REQ']._serialized_end=84
  _globals['_DATA']._serialized_start=86
  _globals['_DATA']._serialized_end=120
  _globals['_ALLDATA']._serialized_start=122
  _globals['_ALLDATA']._serialized_end=149
  _globals['_DATAREQUEST']._serialized_start=151
  _globals['_DATAREQUEST']._serialized_end=269
  _globals['_POINTS']._serialized_start=271
  _globals['_POINTS']._serialized_end=295
  _globals['_CENT_P']._serialized_start=297
  _globals['_CENT_P']._serialized_end=340
  _globals['_DATARESPONSE']._serialized_start=342
  _globals['_DATARESPONSE']._serialized_end=392
  _globals['_MAPPER']._serialized_start=394
  _globals['_MAPPER']._serialized_end=474
  _globals['_REDUCER']._serialized_start=476
  _globals['_REDUCER']._serialized_end=523
# @@protoc_insertion_point(module_scope)
